FROM ruby:3.4.7
ENV LANG C.UTF-8
ENV TZ Asia/Tokyo
ENV RAILS_ENV=development
RUN apt-get update -qq && apt-get install -y \
	build-essential \
	libpq-dev \
	vim \
	libvips \
	&& rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY Gemfile Gemfile.lock ./
RUN bundle install
COPY . .
